package swim.network.rpcprotocol;


public enum RequestType {
    LOGIN, LOGOUT, GET_DESKUSER_BY_EMAIL, ADD_REGISTRATION, GET_CONTESTANTS, GET_EVENTS, GET_CONTESTANTS_NUMBER, GET_SUBMITTED_CONTESTANTS, GET_SUBMITTED_EVENTS;
}
