package swim.network.rpcprotocol;


public enum ResponseType {
    OK, ERROR, LOGIN, LOGOUT, GET_DESKUSER_BY_EMAIL, GET_EVENTS, GET_CONTESTANTS, GET_SUBMITTED_CONTESTANTS, GET_SUBMITTED_EVENTS, GET_CONTESTANTS_NUMBER, GET_REGISTRATIONS, UPDATE_REGISTRATIONS, UPDATE_CONTESTANTS;
}
